server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes[0]:
            id: note-service
            uri: lb://note-service
            predicates[0]: Path=/api/notes/**
            filters[0]: RemoveRequestHeader=Cookie
          routes[1]:
            id: user-service
            uri: lb://user-service
            predicates[0]: Path=/api/users/**
            filters[0]: RemoveRequestHeader=Cookie

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka # to register eureka





